contracts/BaseProvider/BaseLockDealProvider.sol, contracts/DealProvider/DealProvider.sol, contracts/DealProvider/DealProviderModifiers.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/Provider/ProviderModifiers.sol, contracts/TimedLockDealProvider/TimedLockDealProvider.sol, test/BaseLockDealProvider.js, test/LockDealNFT.js, test/TimedLockDealProvider.js
=> removed double requires

contracts/BaseProvider/BaseLockDealProvider.sol, contracts/DealProvider/DealProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/TimedLockDealProvider/TimedLockDealProvider.sol, contracts/interface/IProvider.sol, test/DealProvider.js
=> added isFinal field to withdraw functions

contracts/BaseProvider/BaseLockDealProvider.sol, contracts/DealProvider/DealProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/TimedLockDealProvider/TimedLockDealProvider.sol, test/BaseLockDealProvider.js, test/DealProvider.js, test/TimedLockDealProvider.js
=> Add tests for getData function and fix the burn issue

test/BaseLockDealProvider.js, test/TimedLockDealProvider.js
=> Fix the timestamp issue on the tests

contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/LockProvider/LockDealProvider.sol, contracts/LockProvider/LockDealState.sol, contracts/TimedDealProvider/TimedDealProvider.sol, contracts/TimedDealProvider/TimedProviderState.sol, test/LockDealProvider.js, test/TimedDealProvider.js
=> provider names changed

contracts/LockDealNFT/LockDealNFT.sol, test/LockDealNFT.js
=> fix assigment dublication

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTState.sol, test/LockDealNFT.ts
=> added getData function to LockDealNFT

contracts/LockDealNFT/LockDealNFT.sol, contracts/test/MockVaultManager.sol, package.json
=> used lowercase vaultManager

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/Provider/BasicProvider.sol, contracts/test/MockVaultManager.sol, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/TimedDealProvider.ts
=> Implement the withdrawal functionality on LockDealBundleProvider contract

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, test/LockDealBundleProvider.ts
=> added provider checks to mint function

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, test/LockDealBundleProvider.ts
=> Update the provider address check

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealBundleProvider/LockDealBundleProviderState.sol
=> Update LockDealBundleProvider state

contracts/DealProvider/DealProvider.sol, contracts/DealProvider/DealProviderState.sol, contracts/DealProvider/IDealProvierEvents.sol, contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockProvider/LockDealProvider.sol, contracts/Provider/BasicProvider.sol, contracts/ProviderInterface/IProviderSingleIdRegistrar.sol, contracts/TimedDealProvider/TimedDealProvider.sol, contracts/test/MockProvider.sol, contracts/test/MockVaultManager.sol, package.json
=> Issue #116

contracts/LockProvider/LockDealProvider.sol, contracts/test/MockProvider.sol, test/LockDealNFT.ts, test/LockDealProvider.ts
=> Add the start time check on LockDealProvider contract

contracts/DealProvider/DealProvider.sol, contracts/DealProvider/IDealProvierEvents.sol, package.json, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealProvider.ts, test/TimedDealProvider.ts
=> Add indexed keyword to BasePoolInfo in NewPoolCreated event

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/test/ERC20Token.sol, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/TimedDealProvider.ts, test/helper.ts
=> remove ERC20 token from project

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/Provider/BasicProvider.sol, contracts/RefundProvider/RefundProvider.sol, test/LockDealNFT.ts
=> Issue #120

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealBundleProvider/LockDealBundleProviderState.sol
It seems that when we do Last Id, it works better on the create (sum only 1 time)
but we are getting complex logic on the split.
when we do the First Id, we need to loop 2 times.
=> add _calcTotalAmount

contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealBundleProvider/LockDealBundleProviderState.sol, contracts/LockDealNFT/LockDealNFT.sol, test/LockDealBundleProvider.ts
=> Update the bundle provider state

contracts/DealProvider/IDealProvierEvents.sol, contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/LockProvider/LockDealProvider.sol, contracts/Provider/BasicProvider.sol, contracts/ProviderInterface/IProvider.sol, contracts/RefundProvider/RefundProvider.sol, contracts/RefundProvider/RefundState.sol, contracts/TimedDealProvider/TimedDealProvider.sol, contracts/test/MockProvider.sol, test/LockDealBundleProvider.ts, test/LockDealNFT.ts, test/TimedDealProvider.ts
=> move BasePoolInfo to IProvider interface

contracts/DealProvider/DealProvider.sol, contracts/LockDealBundleProvider/LockDealBundleProviderState.sol, contracts/LockProvider/LockDealProvider.sol, contracts/Provider/BasicProvider.sol, contracts/ProviderInterface/IProviderSingleIdRegistrar.sol, contracts/TimedDealProvider/TimedDealProvider.sol
=> change memory to calldata

contracts/CollateralProvider/CollateralProvider.sol, contracts/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/Provider/BasicProvider.sol, contracts/ProviderInterface/IProvider.sol, contracts/ProviderInterface/IProviderSingleIdRegistrar.sol, contracts/RefundProvider/RefundProvider.sol
=> move registerPool to IProvider interface

contracts/TimedDealProvider/TimedDealProvider.sol, contracts/TimedDealProvider/TimedProviderState.sol, test/TimedDealProvider.ts
=> better names

contracts/AdvancedProviders/CollateralProvider/CollateralModifiers.sol, contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/LockDealNFT/ILockDealNFTEvents.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, contracts/mock/MockProvider.sol, test/LockDealBundleProvider.ts, test/LockDealNFT.ts
=> update provider type from address to IProvider

contracts/LockDealNFT/LockDealNFT.sol
=> remove setPoolIdToProvider

contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/LockDealNFT/LockDealNFT.sol
=> remove setPoolIdToVaultId

contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProviderState.sol, contracts/mock/MockProvider.sol, test/LockDealBundleProvider.ts
=> added registerPool function, refactoring

contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol
=> added valid Params length to registerPool

contracts/AdvancedProviders/CollateralProvider/CollateralState.sol, contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProviderState.sol, contracts/AdvancedProviders/RefundProvider/RefundState.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/SimpleProviders/DealProvider/DealProvider.sol, contracts/SimpleProviders/LockProvider/LockDealProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, contracts/SimpleProviders/TimedDealProvider/TimedDealProvider.sol, contracts/interfaces/IProvider.sol, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/RefundProvider.ts
=> added getWithdrawableAmount for providers

contracts/LockDealNFT/LockDealNFT.sol, contracts/SimpleProviders/TimedDealProvider/TimedDealProvider.sol, test/DealProvider.ts, test/TimedDealProvider.ts
=> fix split bug

contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/CollateralProvider/CollateralState.sol, contracts/AdvancedProviders/LockDealBundleProvider/LockDealBundleProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundState.sol, contracts/SimpleProviders/DealProvider/DealProvider.sol, contracts/SimpleProviders/LockProvider/LockDealProvider.sol, contracts/SimpleProviders/LockProvider/LockDealState.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, contracts/SimpleProviders/Provider/ProviderModifiers.sol, contracts/SimpleProviders/Provider/ProviderState.sol, contracts/SimpleProviders/TimedDealProvider/TimedDealProvider.sol, contracts/interfaces/IProvider.sol, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealProvider.ts, test/RefundProvider.ts, test/TimedDealProvider.ts
=> added names for each provider

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/LockDealNFT/LockDealNFTState.sol, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealBundleProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/RefundProvider.ts, test/TimedDealProvider.ts
=> add baseURI

contracts/LockDealNFT/ILockDealNFTEvents.sol, contracts/LockDealNFT/LockDealNFTState.sol, test/LockDealNFT.ts
=> added BaseURIChanged event

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, test/LockDealNFT.ts
=> added onlyPoolOwner modifier

contracts/AdvancedProviders/BundleProvider/BundleProvider.sol, contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/SimpleProviders/DealProvider/DealProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, test/DealProvider.ts, test/LockDealNFT.ts, test/RefundProvider.ts
=> added MetadataUpdate and BatchMetadataUpdate events

test/helper.ts
=> fix codefactor

contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, test/DealProvider.ts
=> remove MetadataUpdate from creation fucntions

contracts/AdvancedProviders/BundleProvider/BundleProvider.sol, contracts/AdvancedProviders/BundleProvider/BundleProviderState.sol, contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/LockDealNFT/ILockDealNFTEvents.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/SimpleProviders/DealProvider/DealProvider.sol, contracts/SimpleProviders/LockProvider/LockDealProvider.sol, contracts/SimpleProviders/LockProvider/LockDealState.sol, contracts/SimpleProviders/Provider/ProviderState.sol, contracts/SimpleProviders/TimedDealProvider/TimedDealProvider.sol, contracts/SimpleProviders/TimedDealProvider/TimedProviderState.sol, contracts/interfaces/ILockDealNFT.sol, contracts/mock/MockProvider.sol
=> added ILockDealNFT interface

contracts/LockDealNFT/LockDealNFTState.sol, test/LockDealNFT.ts
=> add supportsInterface

contracts/AdvancedProviders/BundleProvider/BundleProvider.sol, contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/CollateralProvider/CollateralState.sol, contracts/AdvancedProviders/CollateralProvider/IInnerWithdraw.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/SimpleProviders/LockProvider/LockDealProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, contracts/SimpleProviders/TimedDealProvider/TimedDealProvider.sol, contracts/interfaces/ILockDealNFT.sol, contracts/interfaces/IProvider.sol, test/BundleProvider.ts, test/CollateralProvider.ts, test/LockDealNFT.ts, test/RefundProvider.ts
=> remove prams in withdraw

contracts/mock/MockProvider.sol, test/TDD.ts
=> test-driven development

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/mock/MockVaultManager.sol, package.json, test/LockDealNFT.ts
=> add enable/disable for transfers

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTInternal.sol, contracts/LockDealNFT/LockDealNFTState.sol
=> added LockDealNFTInternal with internals

contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTState.sol
=> replace setBaseURI function to LockDealNFT

contracts/AdvancedProviders/BundleProvider/BundleProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/SimpleProviders/Provider/BasicProvider.sol, contracts/SimpleProviders/Provider/ProviderModifiers.sol, contracts/mock/MockProvider.sol, test/BundleProvider.ts, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/RefundProvider.ts, test/TDD.ts, test/TimedDealProvider.ts
=> added addresses arrays

contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, test/CollateralProvider.ts
=> copyVaultId inside CollateralProvider

contracts/AdvancedProviders/BundleProvider/BundleModifiers.sol, contracts/AdvancedProviders/BundleProvider/BundleProvider.sol, test/BundleProvider.ts
=> added IERC165 hash check for _createNewSubPool

contracts/LockDealNFT/LockDealNFTState.sol, test/LockDealNFT.ts
=> draft getUserDataByTokens

contracts/AdvancedProviders/RefundProvider/RefundState.sol, test/RefundProvider.ts
=> fix getParams RefundProvider bug

parseGasReport.js
=> update gas table

contracts/LockDealNFT/ILockDealNFTEvents.sol, contracts/LockDealNFT/LockDealNFT.sol, contracts/LockDealNFT/LockDealNFTInternal.sol, contracts/LockDealNFT/LockDealNFTModifiers.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/SimpleProviders/Provider/ProviderModifiers.sol, contracts/interfaces/ILockDealNFT.sol, test/Builder/SimpleBuilder.ts, test/Builder/SimpleRefundBuilder.ts, test/BundleProvider.ts, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/RefundProvider.ts, test/TDD.ts, test/TimedDealProvider.ts
=> update the mapping of approved contracts

contracts/AdvancedProviders/DelayVaultProvider/MigratorV1/DelayVaultMigrator.sol, contracts/LockDealNFT/LockDealNFTState.sol, contracts/interfaces/ILockDealNFT.sol, test/LockDealNFT.ts
Trying to avoid duplicating the getter `vaultManager` address.
=> avoid duplicate vaultManager address

contracts/AdvancedProviders/DelayVaultProvider/DelayVaultProvider.sol, contracts/AdvancedProviders/DelayVaultProvider/DelayVaultState.sol, contracts/AdvancedProviders/DelayVaultProvider/HoldersSum.sol, contracts/AdvancedProviders/DelayVaultProvider/LastPoolOwnerState.sol
Solidity convention recommendations: https://docs.soliditylang.org/en/v0.8.19/style-guide.html#function-argument-names
We should use one naming convention style for the entire project.
=> use camelCase

contracts/LockDealNFT/LockDealNFTState.sol, contracts/interfaces/ILockDealNFT.sol, test/Builder/SimpleRefundBuilder.ts, test/BundleProvider.ts, test/CollateralProvider.ts, test/DealProvider.ts, test/LockDealNFT.ts, test/LockDealProvider.ts, test/RefundProvider.ts, test/TimedDealProvider.ts
=> add name field to BasePoolInfo struct

contracts/AdvancedProviders/RefundProvider/RefundState.sol, test/Builder/SimpleRefundBuilder.ts, test/RefundProvider.ts
=> update RefundProvider getParams

contracts/AdvancedProviders/CollateralProvider/CollateralProvider.sol, contracts/AdvancedProviders/RefundProvider/RefundProvider.sol, contracts/Builders/SimpleRefundBuilder/SimpleRefundBuilder.sol, test/CollateralProvider.ts, test/RefundProvider.ts, test/TDD.ts
=> fix refund main coin bug

contracts/SimpleProviders/LockProvider/LockDealProvider.sol, test/LockDealProvider.ts
=> remove require from `LockDealProvider`

hardhat.config.ts, package-lock.json, package.json, scripts/deploy.ts, scripts/deployProviders.ts
=> update `deployAll` script, add `deployProviders` script
